[2024-01-30T17:36:53.564+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-27T03:00:00+00:00 [queued]>
[2024-01-30T17:36:53.714+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-27T03:00:00+00:00 [queued]>
[2024-01-30T17:36:53.717+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-30T17:36:53.934+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-01-27 03:00:00+00:00
[2024-01-30T17:36:53.973+0000] {standard_task_runner.py:60} INFO - Started process 2523 to run task
[2024-01-30T17:36:53.999+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_api_dag', 'get_weather_data', 'scheduled__2024-01-27T03:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/weather_api_dag.py', '--cfg-path', '/tmp/tmpoe0b95yr']
[2024-01-30T17:36:54.017+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask get_weather_data
[2024-01-30T17:36:54.228+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-27T03:00:00+00:00 [running]> on host 68c8327b56d3
[2024-01-30T17:36:54.910+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_dag' AIRFLOW_CTX_TASK_ID='get_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-27T03:00:00+00:00'
[2024-01-30T17:36:55.871+0000] {logging_mixin.py:188} INFO - {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}
[2024-01-30T17:36:58.001+0000] {logging_mixin.py:188} INFO - {'record': {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}, 'metadata': {'id': '65b933ba1f5677401f287358', 'createdAt': '2024-01-30T17:36:58.018Z', 'private': True, 'name': 'weather_50609c0a-7874-4a05-b9dc-7782d3b6fff0', 'collectionId': '65ab4466266cfc3fde7c6f31'}}
[2024-01-30T17:36:58.016+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-30T17:36:58.108+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_api_dag, task_id=get_weather_data, execution_date=20240127T030000, start_date=20240130T173653, end_date=20240130T173658
[2024-01-30T17:36:58.322+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-30T17:36:58.994+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
