[2024-01-30T17:37:44.473+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-28T08:00:00+00:00 [queued]>
[2024-01-30T17:37:44.546+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-28T08:00:00+00:00 [queued]>
[2024-01-30T17:37:44.548+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-30T17:37:44.669+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-01-28 08:00:00+00:00
[2024-01-30T17:37:44.679+0000] {standard_task_runner.py:60} INFO - Started process 2702 to run task
[2024-01-30T17:37:44.694+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_api_dag', 'get_weather_data', 'scheduled__2024-01-28T08:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/weather_api_dag.py', '--cfg-path', '/tmp/tmp52_sd6_z']
[2024-01-30T17:37:44.709+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask get_weather_data
[2024-01-30T17:37:44.921+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-28T08:00:00+00:00 [running]> on host 68c8327b56d3
[2024-01-30T17:37:45.501+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_dag' AIRFLOW_CTX_TASK_ID='get_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-28T08:00:00+00:00'
[2024-01-30T17:37:46.345+0000] {logging_mixin.py:188} INFO - {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}
[2024-01-30T17:37:47.385+0000] {logging_mixin.py:188} INFO - {'record': {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}, 'metadata': {'id': '65b933ebdc746540189de408', 'createdAt': '2024-01-30T17:37:47.404Z', 'private': True, 'name': 'weather_79f68b77-2e1e-4fe3-899a-c38129471e76', 'collectionId': '65ab4466266cfc3fde7c6f31'}}
[2024-01-30T17:37:47.393+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-30T17:37:47.447+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_api_dag, task_id=get_weather_data, execution_date=20240128T080000, start_date=20240130T173744, end_date=20240130T173747
[2024-01-30T17:37:47.608+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-30T17:37:47.776+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
