[2024-01-30T17:37:48.299+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-28T14:00:00+00:00 [queued]>
[2024-01-30T17:37:48.417+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-28T14:00:00+00:00 [queued]>
[2024-01-30T17:37:48.421+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-30T17:37:48.560+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-01-28 14:00:00+00:00
[2024-01-30T17:37:48.567+0000] {standard_task_runner.py:60} INFO - Started process 2728 to run task
[2024-01-30T17:37:48.579+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_api_dag', 'get_weather_data', 'scheduled__2024-01-28T14:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/weather_api_dag.py', '--cfg-path', '/tmp/tmpzwg2yel2']
[2024-01-30T17:37:48.603+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask get_weather_data
[2024-01-30T17:37:48.906+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-28T14:00:00+00:00 [running]> on host 68c8327b56d3
[2024-01-30T17:37:49.438+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_dag' AIRFLOW_CTX_TASK_ID='get_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T14:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-28T14:00:00+00:00'
[2024-01-30T17:37:51.101+0000] {logging_mixin.py:188} INFO - {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}
[2024-01-30T17:37:53.404+0000] {logging_mixin.py:188} INFO - {'record': {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}, 'metadata': {'id': '65b933f1266cfc3fde8362d1', 'createdAt': '2024-01-30T17:37:53.407Z', 'private': True, 'name': 'weather_2b257249-d692-477e-a8e7-322c82030deb', 'collectionId': '65ab4466266cfc3fde7c6f31'}}
[2024-01-30T17:37:53.419+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-30T17:37:53.491+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_api_dag, task_id=get_weather_data, execution_date=20240128T140000, start_date=20240130T173748, end_date=20240130T173753
[2024-01-30T17:37:53.597+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-30T17:37:53.669+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
