[2024-01-30T17:38:05.853+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-29T00:00:00+00:00 [queued]>
[2024-01-30T17:38:05.955+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-29T00:00:00+00:00 [queued]>
[2024-01-30T17:38:05.967+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-30T17:38:06.548+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-01-29 00:00:00+00:00
[2024-01-30T17:38:06.557+0000] {standard_task_runner.py:60} INFO - Started process 2799 to run task
[2024-01-30T17:38:06.587+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_api_dag', 'get_weather_data', 'scheduled__2024-01-29T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/weather_api_dag.py', '--cfg-path', '/tmp/tmpaaom0v0h']
[2024-01-30T17:38:06.604+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask get_weather_data
[2024-01-30T17:38:06.867+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_api_dag.get_weather_data scheduled__2024-01-29T00:00:00+00:00 [running]> on host 68c8327b56d3
[2024-01-30T17:38:07.329+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_dag' AIRFLOW_CTX_TASK_ID='get_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-29T00:00:00+00:00'
[2024-01-30T17:38:07.963+0000] {logging_mixin.py:188} INFO - {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}
[2024-01-30T17:38:11.183+0000] {logging_mixin.py:188} INFO - {'record': {'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}, 'metadata': {'id': '65b93403266cfc3fde8362e6', 'createdAt': '2024-01-30T17:38:11.188Z', 'private': True, 'name': 'weather_0cf9bda7-c69a-4d92-9949-d8144bdcc08a', 'collectionId': '65ab4466266cfc3fde7c6f31'}}
[2024-01-30T17:38:11.190+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-30T17:38:11.223+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_api_dag, task_id=get_weather_data, execution_date=20240129T000000, start_date=20240130T173805, end_date=20240130T173811
[2024-01-30T17:38:11.322+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-30T17:38:11.401+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
